[package]
name = "payments_api_extensions"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "payments_api_extensions"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.2"
